In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
np.random.randn(1,4)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862]])

In [4]:
np.random.randn(1,4)

array([[ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ]])

In [5]:
np.random.seed(1)

In [6]:
np.random.randn(1,4)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862]])

In [7]:
np.random.seed(2)
np.random.randn(1,4)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081]])

In [8]:
np.random.randn(1,4)

array([[-1.79343559, -0.84174737,  0.50288142, -1.24528809]])

In [11]:
np.random.seed(1)
print(np.random.randn(1,4))
np.random.randn(1,4)

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]]


array([[ 0.86540763, -2.3015387 ,  1.74481176, -0.7612069 ]])

In [ ]:
np.random.seed(3)
for i in range(1,4):
    print(np.random.randn(1,4))
for i in range(1,4):
    print(np.random.randn(1,4))
    