In [2]:
import numpy as np

In [3]:
import matplotlib

In [4]:
r = -4*np.random.rand()

In [5]:
r

-2.2911534149289032

In [10]:
X = np.eye(6)

In [11]:
X

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [37]:
Y = np.array([[1],[2],[3],[4],[5],[4],[3],[2],[1],[3],[0]])
Y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [4],
       [3],
       [2],
       [1],
       [3],
       [0]])

In [38]:
Y.reshape(-1)

array([1, 2, 3, 4, 5, 4, 3, 2, 1, 3, 0])

In [39]:
Y = np.eye(6)[Y.reshape(-1)].T

In [40]:
Y

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])