In [1]:
import numpy as np

In [6]:
np.random.seed(1)
A1 = np.random.randn(1, 3)

print('A1:',A1)
D1 = np.random.rand(A1.shape[0], A1.shape[1])
print('D1:',D1)

keep_prob = 0.5
D1 = D1 < keep_prob
print(D1)

#A1 = 0.01
print('A1:', A1)
A1 = A1 * D1
print('A1:', A1)
A1 = A1 / keep_prob
print(A1)

A1: [[ 1.62434536 -0.61175641 -0.52817175]]
D1: [[ 0.39676747  0.53881673  0.41919451]]
[[ True False  True]]
A1: [[ 1.62434536 -0.61175641 -0.52817175]]
A1: [[ 1.62434536 -0.         -0.52817175]]
[[ 3.24869073 -0.         -1.0563435 ]]


In [2]:
A = np.array([2,5,0,7,0,4，])

In [3]:
A

array([2, 5, 0, 7, 0, 4])

In [4]:
np.int64(A>0)

array([1, 1, 0, 1, 0, 1], dtype=int64)

In [27]:
permutation = list(np.random.permutation(20))

In [28]:
permutation

[2, 12, 11, 10, 3, 14, 0, 7, 15, 8, 4, 19, 6, 1, 9, 16, 17, 18, 13, 5]

In [29]:
A = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
A

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
shuffled_X = A[:,permutation]

IndexError: index 2 is out of bounds for axis 1 with size 1