In [8]:
import numpy as np
A = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
A
B = np.array([[1,2,3,4,5,6,7,8,9]])
B

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
m = B.shape[1]
m

9

In [10]:
permutation = list(np.random.permutation(9))
permutation

[6, 8, 7, 3, 1, 2, 5, 4, 0]

In [11]:
B[:,permutation]

array([[7, 9, 8, 4, 2, 3, 6, 5, 1]])

In [18]:
B[:,permutation].reshape(1,9)

array([[7, 9, 8, 4, 2, 3, 6, 5, 1]])

In [12]:

C= np.array([1,2,3,4,5,6,7,8,9])
C

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(C)

numpy.ndarray

In [14]:
type(B)

numpy.ndarray

In [17]:
D= np.array(1,)
D

array(1)